language: Python 

sudo: required

services:
  - docker
  
notifications:
  email:
    recipients:
    - qzhang@anl.gov
    on_success: never
    on_failure: always
    
branches:
  only:
    - master

before_install:
    - docker version
    - python --version

install:
    - git clone https://github.com/kbase/jars
    - git clone https://github.com/kbase/kb_sdk
    - cd kb_sdk
    - make
    - make sdkbase
    - docker images
    - export PATH=$(pwd)/bin:$PATH
    - cd ../
    - git clone https://github.com/kbaseapps/kb_Metrics.git
    - cd kb_Metrics
    # run the kb-sdk test command once to build test_local dir and populate the .ignore files
    - kb-sdk test -s || true

script:
  - kb-sdk validate
